Name: Squads-fsm-Overlord
IconPath: Squads.png
SoundPath: 
Description: |
    Création de petites esquades polyvalentes pour sécuriser des points clés.
BrainsPackage: brains
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
